# Generated by Django 4.1 on 2022-08-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivTopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sub_titulo', models.TextField()),
                ('imagem', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
