# Generated by Django 4.1 on 2022-09-04 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_divtopo_data_criacao_produto_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link',
            field=models.CharField(blank=True, default='https://www.instagram.com/forchela.andercorrea/', max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
