# Generated by Django 4.1 on 2022-08-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivBaixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('imagem1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('imagem2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('imagem3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='DivInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(max_length=255)),
                ('texto1', models.TextField()),
                ('titulo2', models.CharField(max_length=255)),
                ('texto2', models.TextField()),
                ('titulo3', models.CharField(max_length=255)),
                ('texto3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DivMeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DivTopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sub_titulo', models.TextField()),
            ],
        ),
    ]
