# Generated by Django 4.1 on 2022-08-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Insira por ex: (11)9999-9999', max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('link_instagram', models.CharField(max_length=255)),
                ('link_facebook', models.CharField(max_length=255)),
            ],
        ),
    ]
