# Generated by Django 4.1 on 2022-08-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(help_text='Insira por ex: forchela@gmail.com', max_length=255),
        ),
    ]
