# Generated by Django 4.1 on 2022-08-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_divbaixo_data_criacao_divinformacao_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='telefone',
            field=models.CharField(help_text='Insira por ex: (11)9999-9999', max_length=14),
        ),
    ]
