# Generated by Django 4.1 on 2022-09-01 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreNos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='divbaixo',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='divmeio',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='divtopo',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
